# Generated by Django 4.0.3 on 2022-03-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_hello_hello_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='img/about/'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='cover_hello',
            field=models.ImageField(upload_to='img/hello/'),
        ),
    ]
