# Generated by Django 4.0.3 on 2022-04-01 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_about_image_alter_hello_cover_hello'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/about/'),
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random', models.CharField(blank=True, max_length=128)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.about')),
            ],
        ),
    ]
