# Generated by Django 4.0.3 on 2022-04-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_certificate_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='mainapp.about'),
        ),
    ]
