# Generated by Django 4.0.3 on 2022-04-02 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_facts_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='tools/')),
            ],
        ),
        migrations.CreateModel(
            name='UseTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=64)),
                ('tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tools')),
            ],
        ),
    ]
