# Generated by Django 4.0.3 on 2022-04-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_tools_usetools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usetools',
            name='tools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='mainapp.tools'),
        ),
    ]
